// Autogenerated by Nightwatch
// Refer to the online docs for more details: https://nightwatchjs.org/gettingstarted/configuration/
const chromedriver = require('chromedriver')

module.exports = {
  
  src_folders: ['tests'],

  webdriver: {
    start_process: true,
    server_path: chromedriver.path,
    port: 9515
  },

  test_settings: {
    default: {
      desiredCapabilities: {
        browserName : 'chrome'
      },
    },
  }
};